name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        java-version:
          - 1.8
          - 11
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit Test
        run: mvn -P Unittest -B verify --file pom.xml

  acceptance-test:
    needs: unit-test
    strategy:
      matrix:
        splunk-version:
          - "8.0"
          - "latest"
    runs-on: ubuntu-latest
    container: maven:3-jdk-8

    services:
      splunk:
        image: splunk/splunk:${{matrix.splunk-version}}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_PASSWORD: changed!
        options: --name splunk
        ports:
          - 8089
          - 8088
          - 5555
          - 15000
          - 10667
          - 10668/udp
        volumes:
          - ${{ github.workspace }}/resources:/usr/local/test

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Restart Splunk with Volume Mounted
        uses: docker://docker
        with:
          args: docker restart splunk
      - name: Wait for Splunk Restart
        run: sleep 30
      - name: Acceptance Test
        run: mvn -P AcceptanceTest -B verify --file pom.xml
        env:
          SPLUNK_PASSWORD: changed!
          SPLUNK_HOST: splunk